title: Physical Computing with Python
hero_image: images/cover.png
subtitle: Getting started with physical computing
description: Get started with physical computing on the Raspberry Pi using Python.
original_url: https://www.raspberrypi.org/learning/physical-computing-with-python/
theme: green
duration: 2
copyedit: true
listed: true
ingredient: false
curriculum: creator, design-0, programming-1, phys-comp-1, manufacture-0, community-0
technologies: python
steps:
  - title: Introduction
  - title: What you will need
  - title: GPIO pins
  - title: Lighting an LED
  - title: Switching an LED on and off
  - title: Flashing an LED
  - title: Using buttons to get input
  - title: Manually controlling the LED
  - title: Making a switch
  - title: What next?
